name: Test
on:
  pull_request:
    paths-ignore: "*.rst"
  push:
    paths-ignore: "*.rst"
    branches: [master, develop]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Python 3.8 is the last non-EOL version. Also adapt tox.ini
        python-version: ['3.8', 'pypy3.10', '3.12']
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: '**/test-requirements'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
          python -m pip install 'tox-gh-actions<4.0.0'
      - name: Test with tox
        run: tox
